@host= http://localhost:8080

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "firstName",
    "LastName": "LastName",
    "email": "hello@hello.am",
    "password": "hello123!"
}