@host= http://localhost:8080

GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCdWJlckRpbm5lciIsImlzcyI6IkJ1YmVyRGlubmVyIiwiZXhwIjoxNzg3NTY1OTAzLCJzdWIiOiIwYzhiOGE4ZS1lMmIxLTQ3ZWItODkzOC0zMWZmYTY5OTk1MWYiLCJnaXZlbl9uYW1lIjoiZmlyc3ROYW1lIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZSIsImp0aSI6IjJhZDYwZmQ0LTdjMWEtNGIzNi1iNDA4LWEyZDNkMWIyZTY3MSIsImlhdCI6MTc4NzU2MjMwMywibmJmIjoxNzg3NTYyMzAzfQ.FWjZeiRdVpUByTYFYHxk6kNeOzKqpKUnuo3xDQ2MC7Y